```
[Title] Good/Bad Prediction using MLP Classification with Tensorflow.Keras
[Author] Yibeck Lee(yibec.Lee@gmail.com)
[Contents]
 - Multi-Layer Perceptron Classification for Good/Bad Prediction
```

In [1]:
"""
    A simple neural network written in Keras (TensorFlow backend) to classify the IRIS data
"""

import numpy as np

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
import pandas as pd



Using TensorFlow backend.


In [2]:
# data = load_iris() # load the iris dataset
trainDf = pd.read_csv("../data_source/data01-train.csv", header=None)
#trainDf


In [3]:
(10000 - trainDf[1].sum())/10000

0.721

In [4]:
train_data = trainDf.values

trainFEATURES = train_data[:,4:]
trainFEATURES[:5,]
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(trainFEATURES)
trainFEATURES= scaler.transform(trainFEATURES)


In [5]:
trainLABEL = train_data[:,1]
trainLABEL = trainLABEL.reshape(-1,1)
trainLABEL

array([[0.],
       [1.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [6]:
encoder = OneHotEncoder(sparse=False)
trainLABEL = encoder.fit_transform(trainLABEL)
trainLABEL

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


array([[1., 0.],
       [0., 1.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [7]:
model = Sequential()

model.add(Dense(123, input_shape=(9,), activation='relu', name='fc1'))
model.add(Dense(123, activation='relu', name='fc2'))
model.add(Dense(123, activation='relu', name='fc3'))
model.add(Dense(2, activation='softmax', name='output'))


Instructions for updating:
Colocations handled automatically by placer.


In [1]:

# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(trainFEATURES, trainLABEL, verbose=2, batch_size=100, epochs=100)

# Test on unseen data

results = model.evaluate(trainFEATURES, trainLABEL)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))


NameError: name 'Adam' is not defined

In [69]:
# data = load_iris() # load the iris dataset
testDf = pd.read_csv("../data_source/data01-test.csv", header=None)
#testDf

In [90]:
(10000 - testDf[1].sum())/10000

0.7183

In [91]:
test_data = trainDf.values

testFEATURES = test_data[:,4:]
testFEATURES[:5,]
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(testFEATURES)
testFEATURES= scaler.transform(testFEATURES)

In [92]:
testLABEL = test_data[:,1]
testLABEL = testLABEL.reshape(-1,1)
#testLABEL

In [93]:
encoder = OneHotEncoder(sparse=False)
testLABEL = encoder.fit_transform(testLABEL)
#testLABEL

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [74]:
#model = Sequential()

#model.add(Dense(256, input_shape=(9,), activation='relu', name='fc1'))
#model.add(Dense(256, activation='relu', name='fc2'))
#model.add(Dense(256, activation='relu', name='fc3'))
#model.add(Dense(2, activation='softmax', name='output'))

In [ ]:
# Adam optimizer with learning rate of 0.001
optimizer = Adam(lr=0.001)
model.compile(optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

print('Neural Network Model Summary: ')
print(model.summary())

# Train the model
model.fit(trainFEATURES, trainLABEL, verbose=2, batch_size=100, epochs=100)

# Test on unseen data

results = model.evaluate(testFEATURES, testLABEL)

print('Final test set loss: {:4f}'.format(results[0]))
print('Final test set accuracy: {:4f}'.format(results[1]))

Neural Network Model Summary: 
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
fc1 (Dense)                  (None, 123)               1230      
_________________________________________________________________
fc2 (Dense)                  (None, 123)               15252     
_________________________________________________________________
fc3 (Dense)                  (None, 123)               15252     
_________________________________________________________________
output (Dense)               (None, 2)                 248       
Total params: 31,982
Trainable params: 31,982
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/100
 - 1s - loss: 0.1495 - acc: 0.9399
Epoch 2/100
 - 0s - loss: 0.1409 - acc: 0.9423
Epoch 3/100
 - 0s - loss: 0.1359 - acc: 0.9447
Epoch 4/100
 - 0s - loss: 0.1329 - acc: 0.9462
Epoch 5/100
 - 0s - loss: 0.1324 - acc: 0.9467

In [96]:
GOOD_BAD_PROB = model.predict(testFEATURES)
GOOD_BAD_PROB

array([[9.75149214e-01, 2.48508211e-02],
       [2.01376427e-09, 1.00000000e+00],
       [9.85905111e-01, 1.40949357e-02],
       ...,
       [1.00000000e+00, 4.26575138e-12],
       [9.99986649e-01, 1.33022013e-05],
       [8.77361238e-01, 1.22638755e-01]], dtype=float32)

In [97]:
GOOD_BAD_PREDICTION = np.argmax(GOOD_BAD_PROB,axis=1)
GOOD_BAD_PREDICTION[2]

0

In [98]:

for i in range(10):
    print(testLABEL[i], np.argmax(testLABEL[i]), GOOD_BAD_PREDICTION[i])


[1. 0.] 0 0
[0. 1.] 1 1
[1. 0.] 0 0
[0. 1.] 1 1
[1. 0.] 0 0
[1. 0.] 0 0
[0. 1.] 1 1
[1. 0.] 0 0
[0. 1.] 1 1
[1. 0.] 0 0


In [88]:
miss = np.argmax(testLABEL, axis=1) - GOOD_BAD_PREDICTION
print(abs(miss).sum())

416
